# Generated by Django 5.0.1 on 2024-01-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]