# Generated by Django 4.2.9 on 2024-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(upload_to='images', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/default/profile.png', upload_to='images', verbose_name='profile image'),
        ),
    ]
