# Generated by Django 4.2.9 on 2024-08-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0004_alter_gallery_image_alter_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('content', models.TextField(help_text='Content of the share')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the content was shared')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the content was last updated')),
                ('share_count', models.PositiveIntegerField(default=0, help_text='Number of times this content has been shared')),
                ('id_share', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('likes', models.ManyToManyField(blank=True, help_text='Users who liked the share', related_name='liked_shares', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who shared this content', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Share',
                'verbose_name_plural': 'Shares',
            },
        ),
    ]
