# Generated by Django 4.2.9 on 2024-08-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_alter_post_admin_approved_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='home_app.post'),
        ),
    ]
