# Generated by Django 4.2.9 on 2024-08-24 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_share_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=uuid.uuid4, upload_to='images', verbose_name='image'),
        ),
    ]
